version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"